# Generated by Django 4.2.27 on 2026-01-06 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0006_alter_phoneverification_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 9, 2, 47, 702527, tzinfo=datetime.timezone.utc)),
        ),
    ]
