# Generated by Django 4.2.27 on 2026-01-08 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0007_alter_phoneverification_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 15, 56, 14, 452996, tzinfo=datetime.timezone.utc)),
        ),
    ]
