# Generated by Django 4.2.27 on 2026-01-09 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0009_alter_phoneverification_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 16, 13, 13, 573982, tzinfo=datetime.timezone.utc)),
        ),
    ]
