# Generated by Django 4.2.27 on 2026-01-12 08:21

import app_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0010_alter_phoneverification_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='valid_until',
            field=models.DateTimeField(default=app_login.models.email_otp_expiry),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=app_login.models.phone_otp_expiry),
        ),
    ]
