# Generated by Django 5.2.5 on 2025-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerRefNo', models.CharField(max_length=512)),
                ('transactionRefNo', models.CharField(blank=True, max_length=512, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('currencyPair', models.CharField(max_length=10)),
                ('calculationType', models.CharField(default='A', max_length=1)),
                ('preTaxAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quoteId', models.CharField(blank=True, max_length=512, null=True)),
                ('tax1Amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax2Amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax3Amt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('billingAddressId', models.CharField(blank=True, max_length=512, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('transactionOrderID', models.CharField(blank=True, max_length=512, null=True)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
