# Generated by Django 5.2.5 on 2025-10-03 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerRefNo', models.CharField(blank=True, max_length=512, null=True)),
                ('sessionKey', models.CharField(blank=True, max_length=40, null=True)),
                ('currencyPair', models.CharField(max_length=10)),
                ('basePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax1Perc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax2Perc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax3Perc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('isValidated', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
