# Generated by Django 5.2.5 on 2025-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0003_tradebuy_createdat_tradebuy_quotevaliditytime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeBuy',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='basePrice',
            new_name='preTaxAmt',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='value',
            new_name='taxAmount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sessionKey',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='calculationType',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoteId',
            field=models.CharField(blank=True, default='DefaultQuoteID', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax1Amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax2Amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax3Amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='totalAmt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='transactionDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='transactionOrderID',
            field=models.CharField(blank=True, default='DefaultOrderID', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='transactionType',
            field=models.CharField(default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currencyPair',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customerRefNo',
            field=models.CharField(blank=True, default='DummyRefNo', max_length=512, null=True),
        ),
    ]
