# Generated by Django 5.2.5 on 2025-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0004_delete_tradebuy_rename_baseprice_quote_pretaxamt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
