# Generated by Django 5.2.5 on 2025-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0005_alter_quote_createdat_alter_quote_transactiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='taxType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
