# Generated by Django 5.2.5 on 2025-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0006_quote_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='unitPriceAmt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
